### ISSUE TITLE
Dataframe index issues in boldblast_coi.py, with workaround

### ISSUE THREAD

**Issue by ingotron** [lokalmatador123/BOLDigger#5]
Kudos for creating BOLDigger! This is the smoothest way to use BOLD I have encountered so far.
I encountered this error while trying to launch the Boldigger GUI from PowerShell:

> PS C:\Users\username> boldigger
> Traceback (most recent call last):
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\Scripts\boldigger.exe\__main__.py", line 7, in <module>
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\__main__.py", line 70, in main
>     boldblast_coi.main(session, values['fasta_path'], values['output_folder'], values['batch_size'])
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\boldblast_coi.py", line 247, in main
>     dataframes = save_as_df(html_list, sequences_names[querys.index(query)])
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\boldblast_coi.py", line 105, in save_as_df
>     cols = dataframes[index].columns.tolist()
> UnboundLocalError: local variable 'index' referenced before assignment

The same issue occurred under Windows 10 and Ubuntu 18.04 with Python 3.8.5 and a fresh install of Boldigger 1.2.1. Looking at line 105 in boldblast_coi.py, there is potential for a variable scope error:

```python
    ## save columns before to sort them after
    cols = dataframes[index].columns.tolist()
```

This 'index' is the iterator variable in the preceding for...range loop. I inserted an explicit 'index = 0' before the loop, which lets the GUI launch. However, when I try to run the IDS query, I get a new error in the same statement:

> PS C:\Users\username> boldigger
> Traceback (most recent call last):
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\Scripts\boldigger.exe\__main__.py", line 7, in <module>
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\__main__.py", line 70, in main
>     boldblast_coi.main(session, values['fasta_path'], values['output_folder'], values['batch_size'])
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\boldblast_coi.py", line 248, in main
>     dataframes = save_as_df(html_list, sequences_names[querys.index(query)])
>   File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\boldigger\boldblast_coi.py", line 106, in save_as_df
>     cols = dataframes[index].columns.tolist()
> IndexError: list index out of range

I think the root of the problem this time was that my COI FASTA file included some sequences that are too short for IDS; six sequences out of 3747 were shorter than 30 nt, and any batch of 100 sequences containing these failed to process. Somehow that led to 'dataframes' being assigned an empty list (verified by 'print(len(dataframes))' ) instead of 'nomatch_df'. This issue was partially fixable by adding a check for 'dataframes' being empty:

```python
    ## add process IDs to published sequence
    **index = 0**
    for index in range(len(dataframes)):
        {...}

    ## save columns before to sort them after
    cols = dataframes[index].columns.tolist() **if len(dataframes) > 0 else []**
    ## add sequence names to dataframes
    for index in range(len(dataframes)):
        {...}
```

With the additions in boldface, BOLDigger completed successfully, although batches including reads too short for IDS led to empty dataframes, effectively skipping that batch. Adding additional data and selecting best hits for the downloaded hits worked without issues.

I have not investigated the scripts for the other databases in detail, but if the same code was used for 'save_as_df', the same problem could occur for ITS and rbcL/Matk.

**Comment by DominikBuchner** [comment]
Hi,
thanks for the detailed description of the issue. 
The problem is the "bad" .fasta file. When sending an Identification Request to BOLD with the batch containing the short sequences, the bold servers send back an empty response, leading to the dataframe being empty and this index out of bounds error (You can actually test it manually for that batch through the website, you will get a notification that sequences must be at least 80 bp long).
I think the correct workaround for this is to check the .fasta file before any request is send and:
a) Inform the user that there is an issue with some sequences (and best, point to these sequences directly)
b1) Either remove these sequences (which will probably lead to a species list not matching the OTU table) or
b2) Replace these sequences with a placeholder.

I will add this one to the todo list, so expect a fix within the next couple of days!

**Comment by bwprice** [comment]
Hi Dominik - great program! I'm getting a similar error as described above (Windows 10), and I installed BOLDigger today. I can't see any issue with the fasta file (all 658bp long, no weird names). The seq I'm checking have the odd ambiguous base (N) but they work fine when searched directly through BOLD and some with "N" worked fine in BOLDigger so I don't think that's the issue...
Any ideas? Error below and fasta file attached.

[Ainsdale_run1_barcodes.zip](https://github.com/DominikBuchner/BOLDigger/files/6218066/Ainsdale_run1_barcodes.zip)


C:\WINDOWS\system32>boldigger
Traceback (most recent call last):
  File "c:\users\benjp\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\benjp\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\benjp\AppData\Local\Programs\Python\Python39\Scripts\boldigger.exe\__main__.py", line 7, in <module>
  File "c:\users\benjp\appdata\local\programs\python\python39\lib\site-packages\boldigger\__main__.py", line 70, in main
    boldblast_coi.main(session, values['fasta_path'], values['output_folder'], values['batch_size'])
  File "c:\users\benjp\appdata\local\programs\python\python39\lib\site-packages\boldigger\boldblast_coi.py", line 247, in main
    dataframes = save_as_df(html_list, sequences_names[querys.index(query)])
  File "c:\users\benjp\appdata\local\programs\python\python39\lib\site-packages\boldigger\boldblast_coi.py", line 105, in save_as_df
    cols = dataframes[index].columns.tolist()
UnboundLocalError: local variable 'index' referenced before assignment

**Comment by DominikBuchner** [comment]
Dear Ben, 
for this specific case I don't know what causes the error but believe it is not related to BOLDigger since I get an exception from the bold servers if I try to search your sequences manually. I agree with you in that it is certainly not the sequences, they are fine. It is also not connected to the sequence length or name of the sequence.
I'm in contact with the BOLD support to fix this, so this can take some time. Please also check if BOLDigger works with other sequences so we can exclude an error on your end. 

All I know up to know is that it's not all of your sequences but some that are causing trouble somehow.
While Plate4_H9 works fine for me the first sequence of your file does throw an exception. 
Since I don't get the pattern here, I can't program a workaround and I'll have to wait for the answer of the BOLD support.

However if you need the data quickly, it is possible to query them via the API (excluding the private hits). If you need any assist with setting this up, I'm happy to help.

![image](https://user-images.githubusercontent.com/38790188/112793002-ccadbe80-9064-11eb-9bc1-1eba98c1d3a1.png)

**Comment by bwprice** [comment]
Hi Dominik,
Thanks for the quick reply. I've managed to get over half done (ie 150/300) using BOLDigger. Thanks for your offer to help run them against BOLD. At the moment when it crashes I'm just cutting out the bad sequence and then re-running the pipeline until I get to the end.
Hopefully BOLD support figures this out :)

**Comment by bwprice** [comment]
Quick update, ran them again without issue - I set the batch size to 1 so no idea what's going on....

**Comment by DominikBuchner** [comment]
Dear Ben,
luckily it wasn't my fault.

"Dear Dominik,


Thank you for contacting us. There may have been some sort of a glitch with our open ID engine. I tried it with your sequences and it worked for me.
Could you please try again? If you encounter the same error, please let me know what parameters you are using and I can look into it again."

So everything should be back to normal and BOLDigger should work fine again.
best Dominik

**Comment by myoung02** [comment]
I'm having the same issue currently - a batch of 100 will immediately produce the same error as listed above. I've switched to a batch of 1, and just the first 9 get processed and by the 10th sequence the error is reproduced. Is it possible that there's currently another issue with BOLD's open ID engine. 

As an aside, boldigger has been a lifesaver this year!

**Comment by DominikBuchner** [comment]
Hi,
do you mind sending me the fasta file via mail so I can check it?
best Dominik

**Comment by myoung02** [comment]
[otus.zip](https://github.com/DominikBuchner/BOLDigger/files/6975669/otus.zip)
Let me know if this works.  I've included two different fasta files I've tried and had issues with. The pos OTUs file I've run previously without issue. 

For reference, I'm on Windows and I get two different errors, one when I try to do a batch of 100, and then another when I change the batch to 1. Both seem to reference the index variable - being out of range or referenced before assignment.

I seem to be able to run both files on the ID Engine (logged in through my BOLD account) no problem so I'm not sure what could be causing the error with boldigger.

**Comment by DominikBuchner** [comment]
[repaired files.zip](https://github.com/DominikBuchner/BOLDigger/files/6976571/repaired.files.zip)

Hi there,
there was something off with the windows linebreak. Windows uses CRLF while unix based systems only use LF. I switched it to the unix version and it works fine. BUT this is something to consider when generating the fasta file itself. I uploaded the files again, they should work now. If you encounter this issue again try to open the fasta with an advanced editor (e.g. Atom, Notepad++) and change the linebreak to LF. Otherwise BOLDigger will try to blast an empty line or a sequence with an empty line added which explains why the error occurs for the last OTU!

I might be able to program a fix for that in the future but I'm to busy atm.

best Dominik

**Comment by myoung02** [comment]
Thanks so much for this! Your fixed files seem to have helped. I've also realized that BOLD has changed the open ID engine to only allow 50 sequences at a time now, which would explain why I was still getting errors when using the standard setting of 100 sequences.

**Comment by DominikBuchner** [comment]
Good to know!

I will Change boldigger accordingly.

Best Dominik

Monica R. Young ***@***.***> schrieb am Do., 12. Aug. 2021,
22:06:
